#!/usr/bin/env python3
"""Render the maintained blog Markdown and inventory without third-party packages.

The editorial subset is paragraphs, headings, links, emphasis and strong text.
Images, descriptions and related posts live in blog/posts.json. Shared page
furniture is read from support.html, which the existing maintenance scripts own.
Run those scripts before rendering after a shared navigation or font change.
"""
import argparse
import hashlib
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORIGIN = 'https://postmello.com'
AUTHOR = 'Patrick Amihood, Creator of Postmello'
POSTS = json.loads((ROOT / 'blog/posts.json').read_text())
BY_SLUG = {post['slug']: post for post in POSTS}
SHARED = (ROOT / 'support.html').read_text()
TOKEN = re.compile(r'(\[[^\]]+\]\([^)]+\)|\*\*[^*]+\*\*|\*[^*]+\*)')


def inline(text):
    pieces = []
    for part in TOKEN.split(text):
        if part.startswith('[') and (match := re.fullmatch(r'\[([^\]]+)\]\(([^)]+)\)', part)):
            label, url = match.groups()
            if not url.startswith(('https://', '/blog/')):
                raise ValueError(f'Unsupported editorial link: {url}')
            pieces.append(f'<a href="{html.escape(url, quote=True)}">{inline(label)}</a>')
        elif part.startswith('**') and part.endswith('**'):
            pieces.append(f'<strong>{html.escape(part[2:-2])}</strong>')
        elif part.startswith('*') and part.endswith('*'):
            pieces.append(f'<em>{html.escape(part[1:-1])}</em>')
        else:
            pieces.append(html.escape(part, quote=False))
    return ''.join(pieces)


def asset_url(path):
    version = hashlib.md5((ROOT / path.lstrip('/')).read_bytes()).hexdigest()[:8]
    return f'{path}?v={version}'


def shell(title, description, path, content, article=False):
    header = re.search(r'<header\b.*?</header>', SHARED, re.S).group()
    footer = re.search(r'<footer\b.*?</footer>', SHARED, re.S).group()
    fonts = '\n  '.join(tag for tag in re.findall(r'<link\b[^>]+>', SHARED)
                        if any(domain in tag for domain in ('fonts.googleapis.com', 'fonts.gstatic.com')))
    title, description = html.escape(title, quote=True), html.escape(description, quote=True)
    canonical = ORIGIN + path
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}{' · Postmello Blog' if article else ''}</title>
  <meta name="description" content="{description}" />
  <link rel="icon" type="image/png" href="/assets/favicon.png" />
  <link rel="apple-touch-icon" href="/assets/app-icon.png" />
  <meta property="og:title" content="{title}" />
  <meta property="og:description" content="{description}" />
  <meta property="og:type" content="{'article' if article else 'website'}" />
  <meta property="og:image" content="{ORIGIN}/assets/og-card.jpg" />
  <meta property="og:url" content="{canonical}" />
  <meta property="og:site_name" content="Postmello" />
  <meta name="twitter:card" content="summary_large_image" />
  <link rel="canonical" href="{canonical}" />
  {fonts}
  <link rel="stylesheet" href="{asset_url('/styles.css')}" />
  <link rel="stylesheet" href="{asset_url('/assets/blog.css')}" />
  <script src="{asset_url('/assets/site.js')}" defer></script>
</head>
<body>
  <!-- Generated by scripts/render-blog.py. Edit index.md and blog/posts.json. -->
  {header}
  <main id="main-content">
{content}
  </main>
  {footer}
</body>
</html>
'''


def figure(data):
    if not (ROOT / data['src'].lstrip('/')).is_file():
        raise ValueError(f"Missing blog image: {data['src']}")
    compact = ' post-figure-compact' if data.get('compact') else ''
    return (f'<figure class="post-figure{compact}">'
            f'<img src="{html.escape(data["src"])}" alt="{html.escape(data["alt"], quote=True)}" '
            f'width="{data["width"]}" height="{data["height"]}" loading="lazy" decoding="async" />'
            f'<figcaption>{html.escape(data["caption"])}</figcaption></figure>')


def article(post):
    source = (ROOT / 'blog' / post['slug'] / 'index.md').read_text()
    blocks = re.split(r'\n\s*\n', source.strip())
    if blocks.pop(0) != '# ' + post['title']:
        raise ValueError(f"Title disagrees with source: {post['slug']}")
    if blocks.pop(0) != f'*By {AUTHOR}*':
        raise ValueError(f"Missing byline: {post['slug']}")
    rendered = [
        '<article class="post">', '<a class="back" href="/blog/">← Postmello Blog</a>',
        f'<h1>{html.escape(post["title"])}</h1>',
        f'<p class="post-deck">{html.escape(post["deck"])}</p>',
        f'<p class="post-meta">By {AUTHOR}</p>',
    ]
    paragraphs = 0
    image = post.get('figure')
    for block in blocks:
        if match := re.fullmatch(r'(#{2,3}) (.+)', block):
            level, title = len(match[1]), match[2]
            anchor = re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')
            rendered.append(f'<h{level} id="{anchor}">{inline(title)}</h{level}>')
        else:
            if re.match(r'^(?:#|[-+] |\d+\. |>|```|!)', block):
                raise ValueError(f"Unsupported Markdown block in {post['slug']}: {block[:60]}")
            rendered.append(f'<p>{inline(" ".join(block.splitlines()))}</p>')
            paragraphs += 1
            if image and paragraphs == image['after_paragraph']:
                rendered.append(figure(image))
    if image and paragraphs < image['after_paragraph']:
        raise ValueError(f"Image position exceeds prose: {post['slug']}")
    rendered.append('<nav class="post-related" aria-label="More from the desk"><h2>Keep reading</h2><ul>')
    for slug in post['related']:
        related = BY_SLUG[slug]
        rendered.append(f'<li><a href="/blog/{slug}/">{html.escape(related["title"])} <span aria-hidden="true">→</span></a></li>')
    rendered.extend(['</ul></nav>', '</article>'])
    return shell(post['title'], post['description'], f'/blog/{post["slug"]}/', '\n'.join(rendered), True)


def index():
    content = ['<div class="blog-index">', '<a class="back" href="/">← Home</a>',
               '<h1>Postmello Blog</h1>',
               '<p class="blog-intro">The reasons behind Postmello, and the decisions that give it its shape.</p>',
               f'<p class="post-meta">Essays by {AUTHOR}</p>']
    for kind, title in [('overview', 'The idea and the design'), ('essay', 'A closer look')]:
        content.extend([f'<section class="blog-section" aria-labelledby="{kind}-heading">',
                        f'<h2 id="{kind}-heading">{title}</h2>', '<ul class="post-list">'])
        for post in POSTS:
            if post['kind'] != kind:
                continue
            url = '/blog/' + post['slug'] + '/'
            content.extend(['<li>', f'<h3><a href="{url}">{html.escape(post["title"])}</a></h3>',
                            f'<p>{html.escape(post["description"])}</p>',
                            f'<a class="editorial-link" href="{url}">Read the essay <span aria-hidden="true">→</span></a>', '</li>'])
        content.extend(['</ul></section>'])
    content.append('</div>')
    return shell('Postmello Blog', 'Essays on friendship, creative letters and the design of a quiet place to write.', '/blog/', '\n'.join(content))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated HTML differs from the sources.')
    args = parser.parse_args()
    if len(BY_SLUG) != len(POSTS):
        raise SystemExit('Duplicate blog slug')
    outputs = {ROOT / 'blog/index.html': index()}
    for post in POSTS:
        outputs[ROOT / 'blog' / post['slug'] / 'index.html'] = article(post)
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit('Blog HTML needs rendering: ' + ', '.join(stale))
    print(f'[blog] {len(POSTS)} articles and index: {"current" if args.check else "rendered"}')


if __name__ == '__main__':
    main()
